image: 'node:18'

test:
  stage: 'test'
  cache:
    key:
      files:
        - 'package-lock.json'
    paths:
      - '.npm/'
  script:
    - 'npm ci --cache .npm --prefer-offline'
    - 'echo "${CI_COMMIT_MESSAGE}" | npm run lint:commit'
    - 'npm run lint:editorconfig'
    - 'npm run lint:prettier'
    - 'npm run lint'
    - 'npm run build'
  only:
    - 'develop'

deploy-production:
  stage: 'deploy'
  script:
    - 'npm install --global vercel'
    - 'vercel --token="${VERCEL_TOKEN}" --prod'
  only:
    - 'main'

deploy-preview:
  stage: 'deploy'
  script:
    - 'npm install --global vercel'
    - 'vercel --token="${VERCEL_TOKEN}" > domain.txt'
    - echo "$(cat domain.txt)"
    - vercel --token="${VERCEL_TOKEN}" alias set "$(cat domain.txt)" "${VERCEL_PREVIEW_URL}"
  only:
    - 'develop'
