image: 'node:18'

cache:
  key:
    files:
      - 'package-lock.json'
  paths:
    - '.npm/'

before_script:
  - 'npm ci --cache .npm --prefer-offline'

test:
  stage: 'test'
  script:
    - 'echo "${CI_COMMIT_MESSAGE}" | npm run lint:commit'
    - 'npm run lint:editorconfig'
    - 'npm run lint:prettier'
    - 'npm run lint'
    - 'npm run build'
  only:
    - 'develop'

deploy-production:
  stage: 'deploy'
  script:
    - 'npm install --global vercel'
    - 'npm run build'
    - 'vercel --token="${VERCEL_TOKEN}" --prod'
  only:
    - 'main'

deploy-preview:
  stage: 'deploy'
  script:
    - 'npm install --global vercel'
    - 'npm run build'
    - 'vercel --token="${VERCEL_TOKEN}" > domain.txt'
    - echo "$(cat domain.txt)"
    - vercel --token="${VERCEL_TOKEN}" alias set "$(cat domain.txt)" "${VERCEL_PREVIEW_URL}"
  only:
    - 'develop'
