image: 'node:18'

cache:
  key:
    files:
      - 'package-lock.json'
  paths:
    - '.npm/'

before_script:
  - 'npm ci --cache .npm --prefer-offline'
  - 'cp apps/api/.env.example apps/api/.env'
  - 'cp apps/website/.env.example apps/website/.env'

lint:
  stage: 'test'
  script:
    - 'npm run lint:editorconfig'
    - 'npm run lint:prettier'
    - 'npm run lint:markdown'
    - 'npm run lint'
  only:
    - 'develop'

test:
  stage: 'test'
  image: 'cypress/base:18.12.1'
  script:
    - 'npm run build'
    - 'npm run test'
  only:
    - 'develop'
