services:
  carolo-api:
    container_name: "carolo-api"
    image: "carolo-api"
    restart: "unless-stopped"
    ports:
      - "9001:9001"
      # - "5555:5555"
    build:
      context: "./"
      dockerfile: "./apps/api/Dockerfile"
    env_file: "./apps/api/.env"
    depends_on:
      - "carolo-database"

  carolo-website:
    container_name: "carolo-website"
    image: "carolo-website"
    restart: "unless-stopped"
    ports:
      - "9000:9000"
    build:
      context: "./"
      dockerfile: "./apps/website/Dockerfile"
    env_file: "./apps/website/.env"

  carolo-database:
    container_name: "carolo-database"
    image: "postgres:16.1"
    restart: "unless-stopped"
    env_file: ".env"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - "carolo-postgres-data:/var/lib/postgresql/data"

volumes:
  carolo-postgres-data:
