services:
  workspace:
    build:
      context: "./"
      dockerfile: "./Dockerfile"
    volumes:
      - "..:/workspace:cached"
    command: "sleep infinity"
    network_mode: "host"

  carolo-database:
    image: "postgres:15.4"
    environment:
      POSTGRES_USER: "carolo_user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "carolo"
    volumes:
      - "carolo-postgres-data:/var/lib/postgresql/data"
    restart: "unless-stopped"
    network_mode: "host"

volumes:
  carolo-postgres-data:
