services:
  workspace:
    build:
      context: './'
      dockerfile: './Dockerfile'
    volumes:
      - '..:/workspace:cached'
    command: 'sleep infinity'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  carolo-database:
    image: 'postgres:15.2'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'carolo'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    restart: 'unless-stopped'

volumes:
  postgres-data:
