name: "ci"

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4.1.1"

      - uses: "pnpm/action-setup@v2.4.0"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v4.0.1"
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: "Install dependencies"
        run: "pnpm install --frozen-lockfile"

      - run: "cp .env.example .env"
      - run: "cp apps/api/.env.example apps/api/.env"
      - run: "cp apps/website/.env.example apps/website/.env"

      - run: "pnpm run build"
      - run: "pnpm run lint"
      - run: 'pnpm run lint:commit -- --to "${{ github.sha }}"'
      - run: "pnpm run lint:editorconfig"
      - run: "pnpm run lint:prettier"
      - run: "pnpm run test"
