name: 'ci'

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3.6.0'

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v3.8.1'
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: 'Install dependencies'
        run: 'npm clean-install'

      - run: 'cp .env.example .env'
      - run: 'cp apps/api/.env.example apps/api/.env'
      - run: 'cp apps/website/.env.example apps/website/.env'

      - run: 'npm run build'
      - run: 'npm run lint'
      - run: 'npm run lint:editorconfig'
      - run: 'npm run lint:prettier'
      - run: 'npm run test'
